### ISSUE TITLE
Not compatible with python 2.x

### ISSUE THREAD

**Issue by truki** [acgallardo/pyQuiz#2]
Not compatible with Python 2.x, because in Python 2.x input() method return a tuple, not a string like Python 3. Then after that isnumeric() fail because isnumeric is a method valid for Python 3 and string types.

A solution could be to specified Python 3 requirement in README.md.

Best   @#regards

**Comment by acgallardo** [comment]
Thanks, but only planned support for python > 3

**Comment by acgallardo** [comment]
Thanks, but only planned support for python > 3
